query SubmissionsByWeek($num: Int = 0, $year: Int, $id: Int = 0) {
  weeks(num: $num, year: $year, id: $id) {
    id
    num
    date
    submissions {
      id
      user {
        name
        id
      }
    }
  }
}
